services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: transaction_push_freqtrade
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade
      --config /freqtrade/user_data/config.btc_eth.dryrun.example.json
      --strategy BtcEth4hStrategy
